# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(0, 0, 501, 421))
        self.main_tab.setObjectName("main_tab")
        self.led_resistor = QtWidgets.QWidget()
        self.led_resistor.setObjectName("led_resistor")
        self.led_type = QtWidgets.QComboBox(self.led_resistor)
        self.led_type.setGeometry(QtCore.QRect(120, 90, 69, 22))
        self.led_type.setObjectName("led_type")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.led_type.addItem("")
        self.no_led = QtWidgets.QLabel(self.led_resistor)
        self.no_led.setGeometry(QtCore.QRect(20, 50, 97, 33))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no_led.setFont(font)
        self.no_led.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.no_led.setObjectName("no_led")
        self.led_count = QtWidgets.QSpinBox(self.led_resistor)
        self.led_count.setGeometry(QtCore.QRect(120, 50, 41, 31))
        self.led_count.setObjectName("led_count")
        self.led_color = QtWidgets.QLabel(self.led_resistor)
        self.led_color.setGeometry(QtCore.QRect(40, 80, 71, 33))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.led_color.setFont(font)
        self.led_color.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.led_color.setObjectName("led_color")
        self.led_cir = QtWidgets.QLabel(self.led_resistor)
        self.led_cir.setGeometry(QtCore.QRect(210, 80, 141, 33))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.led_cir.setFont(font)
        self.led_cir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.led_cir.setObjectName("led_cir")
        self.par_ser = QtWidgets.QComboBox(self.led_resistor)
        self.par_ser.setGeometry(QtCore.QRect(360, 90, 69, 22))
        self.par_ser.setObjectName("par_ser")
        self.par_ser.addItem("")
        self.par_ser.addItem("")
        self.result = QtWidgets.QPlainTextEdit(self.led_resistor)
        self.result.setGeometry(QtCore.QRect(30, 240, 431, 71))
        self.result.setObjectName("result")
        
        self.calculate = QtWidgets.QPushButton(self.led_resistor)
        self.calculate.setGeometry(QtCore.QRect(170, 160, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Mj_Beirut Heading")
        font.setPointSize(11)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.calculate.clicked.connect(self.press_calculate)
        
        self.voltage = QtWidgets.QLabel(self.led_resistor)
        self.voltage.setGeometry(QtCore.QRect(210, 50, 71, 33))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltage.setFont(font)
        self.voltage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.voltage.setObjectName("voltage")
        self.voltage_input = QtWidgets.QPlainTextEdit(self.led_resistor)
        self.voltage_input.setGeometry(QtCore.QRect(290, 50, 61, 31))
        self.voltage_input.setObjectName("voltage_input")
        self.voltage_unit = QtWidgets.QLabel(self.led_resistor)
        self.voltage_unit.setGeometry(QtCore.QRect(360, 50, 21, 33))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voltage_unit.setFont(font)
        self.voltage_unit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.voltage_unit.setObjectName("voltage_unit")
        self.main_tab.addTab(self.led_resistor, "")
        self.res_watt = QtWidgets.QWidget()
        self.res_watt.setObjectName("res_watt")
        self.main_tab.addTab(self.res_watt, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.led_type.setItemText(0, _translate("MainWindow", "قرمز"))
        self.led_type.setItemText(1, _translate("MainWindow", "آبی"))
        self.led_type.setItemText(2, _translate("MainWindow", "زرد"))
        self.led_type.setItemText(3, _translate("MainWindow", "سبز"))
        self.led_type.setItemText(4, _translate("MainWindow", "صورتی"))
        self.led_type.setItemText(5, _translate("MainWindow", "سفید"))
        self.led_type.setItemText(6, _translate("MainWindow", "مادورن قرمز"))
        self.led_type.setItemText(7, _translate("MainWindow", "ماورا بنفش"))
        self.no_led.setText(_translate("MainWindow", "<html><head/><body><p>ها LED تعداد</p></body></html>"))
        self.led_color.setText(_translate("MainWindow", "<html><head/><body><p>LED رنگ</p></body></html>"))
        self.led_cir.setText(_translate("MainWindow", "<html><head/><body><p>ها LED نوع چیدمان</p></body></html>"))
        self.par_ser.setItemText(0, _translate("MainWindow", "سری"))
        self.par_ser.setItemText(1, _translate("MainWindow", "موازی"))
        self.calculate.setText(_translate("MainWindow", "محاسبه"))
        self.voltage.setText(_translate("MainWindow", "<html><head/><body><p>ولتاژ مدار</p></body></html>"))
        self.voltage_unit.setText(_translate("MainWindow", "<html><head/><body><p>v</p></body></html>"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.led_resistor), _translate("MainWindow", "LED مقاومت"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.res_watt), _translate("MainWindow", "توان مقاومت"))

    def press_calculate(self):
        r = int(led_resistor_calculatin() * 1000)
        res = 'مقاومت پیشنهادی برای بهترین روشنایی = ' + str(r) + ' اهم'
        self.result.setPlainText(res)


def led_resistor_calculatin():
    resistor = 0
    vf = 0
    I = 20
    
    vs = float(ui.voltage_input.toPlainText())
    
    
    led_col = ui.led_type.currentIndex()
    led_cir_type = ui.par_ser.currentIndex()
    
    if(led_col == 0):
        vf = 1.8
    elif(led_col == 1):
        vf = 3.2
    elif(led_col == 2):
        vf = 2.1
    elif(led_col == 3):
        vf = 2.2
    elif(led_col == 4):
        vf = 3.2
    elif(led_col == 5):
        vf = 3.2
    elif(led_col == 6):
        vf = 1.2
    elif(led_col == 7):
        vf = 3.2
        
    resistor = (vs - vf) / I
    
    print(resistor)
    
    
    return resistor



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
